(ns editor.st
  (:import (org.stringtemplate.v4 ST
                                  STGroup
                                  STGroupDir
                                  STGroupFile
                                  STGroupString
                                  AttributeRenderer))
  (:import (java.io File))
  (:import (java.util Formatter
                      Locale))
  (:use (editor name-util core)))

(let [hello (ST. "Hello, <name>")]
  (.add hello "name" "World")
  (println (.render hello)))


(let [group (STGroupDir. "./src/editor/tmp")
      st (.getInstanceOf group "decl")]
  (doto st
    (.add "type" "int")
    (.add "name" "x")
    (.add "value" 10))
  (.render st))

(let [group (STGroupFile. "./src/editor/tmp/test.stg")
      st (.getInstanceOf group "decl")]
  (doto st
    (.add "type" "int")
    (.add "name" "x")
    (.add "value" 0))
  (.render st))

(defn make-user [id name]
  (proxy [Object] []
    (getId []
      1)
    (getName []
      2)))

(macroexpand-1 '(proxy [Object] []
    (getId []
      1)
    (getName []
      2)))
;ST st = new ST("<b>$u.id$</b>: $u.name$", '$', '$');
;st.add("u", new User(999, "parrt"));
;;;String result = st.render(); // "<b>999</b>: parrt"
(let [st (ST. "$u$-><b>$u.id$</b>: $u.name$" \$ \$)]
  (.add st "u" (proxy [Object] []
                 (id []
                   (println "ahaha")
                   10)
                 (name []
                   (println "oyaya")
                   "parrt")
                 (toString []
                   (println "myaaa")
                   "abc")))
  (.render st))

;; ST st = new ST("<items:{it|<it.id>: <it.lastName>, <it.firstName>\n}>");
;; st.addAggr("items.{ firstName ,lastName, id }", "Ter", "Parr", 99); // add() uses varargs
;; st.addAggr("items.{firstName, lastName ,id}", "Tom", "Burns", 34);
;; String expecting =
;;         "99: Parr, Ter"+newline +
;;         "34: Burns, Tom"+newline;

(let [st (ST. "<items:{it|<it.id>: <it.lastName>, <it.firstName>\n}>")]
  (doto st
    (.addAggr "items.{ firstName, lastName, id }" (to-array ["Ter" "Parr" 99]) )
    (.addAggr "items.{ firstName, lastName, id }" (to-array ["Tom" "Burns" 34])))
  (.render st))
(type ST)

;; String template =
;;     "foo(x,y) ::= << <x; format=\"%,d\"> <y; format=\"%,2.3f\"> >>\n";
;; STGroup g = new STGroupString(template);
;; g.registerRenderer(Number.class, new NumberRenderer());
;; ST st = group.getInstanceOf("foo");
;; st.add("x", -2100); 
;; st.add("y", 3.14159);
;; String result = st.render(new Locale("pl"));
(def *st-template* "foo(x,y) ::= << <x; format=\",%d\"> <y; format=\"%,2.3f\"> >>\n")

(defn make-rendier []
  (proxy [AttributeRenderer] []
    (toString [o, format-str, locale]
      ;(println o)
      ;(println format-str)
      ;(println locale)
      (if format-str
        (let [f (Formatter. locale)]
          (.format f format-str (to-array [o]))
          (.toString f))
        (.toString o)))))

(let [g (STGroupString. *st-template*)]
  (.registerRenderer g Number (make-rendier))
  (let [st (.getInstanceOf g "foo")]
    (doto st
      (.add "x" -2100)
      (.add "y" 3.14159))
    (.render st (Locale. "pl"))))
(bean Formatter)
(.format (Formatter. (Locale. "pl")) "%4$2s %3$2s %2$2s %1$2s", (to-array [ "a", "b", "c", "d"]))

(def *cpp-component-stg* "st/cpp/component.stg")

(defn gen-cpp-component [comp-key]
  (let [group (STGroupFile. "st/cpp/component.stg")
        st (.getInstanceOf group "component_header")
        bases_st (.getInstanceOf group "bases")
        attributes_st (.getInstanceOf group "attributes")
        getters_and_setters_st (.getInstanceOf group "getters_and_setters")
        class_st (.getInstanceOf group "component_class")]
    (doto bases_st
      (.add "base_list" "IComponent")
      (.add "base_list" "Object")
      (.add "base_list" "HandlableObject"))
    (doto attributes_st
      (.add "types" "int")
      (.add "names" "id_")
      (.add "types" "std::string")
      (.add "names" "name_"))
    (doto getters_and_setters_st
      (.add "types" "int")
      (.add "getters" "GetId")
      (.add "setters" "SetId")
      (.add "m_names" "id_")
      (.add "arg_names" "id")
      (.add "types" "std::string")
      (.add "getters" "GetName")
      (.add "setters" "SetName")
      (.add "m_names" "name_")
      (.add "arg_names" "name"))
    (doto class_st
      (.add "name" (cpp-component-name :base))
      (.add "bases" bases_st)
      (.add "attributes" attributes_st)
      (.add "getters_and_setters" getters_and_setters_st))
    (doto st
      (.add "manifest" "Automatically generated by happy world editor, DO NOT edit by hand.")
      (.add "name" (cpp-component-header-define comp-key))
      (.add "body" class_st))
    (spit "tmp.h" (.render st))))

;(gen-cpp-component :base)
